"use client";

import { Bot, Check, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import type { WorkspacePayload } from "@/components/KeelApp";
import { formatMoney } from "@/lib/finance.mjs";

type Preview={id?:string;kind:"approve_matching"|"set_limit"|"unsupported";summary:string;matches:{id:string;merchant:string;amountMinor:number;currency:string}[]};
export function ApproverCommandDesk({workspace,onChanged,notify}:{workspace:WorkspacePayload;onChanged:()=>Promise<unknown>;notify:(message:string,tone:"success"|"error")=>void}){
  const [prompt,setPrompt]=useState("Approve submitted Travel claims below €100");
  const [consent,setConsent]=useState(false);const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState<"preview"|"execute"|null>(null);
  async function previewCommand(){setBusy("preview");setPreview(null);try{const response=await fetch("/api/approver/commands",{method:"POST",headers:{"content-type":"application/json","x-keel-ai-request":"1"},body:JSON.stringify({mode:"preview",prompt,consent,actorId:workspace.actor.id,actorName:workspace.actor.name})});const payload=await response.json() as {preview?:Preview;error?:string};if(!response.ok||!payload.preview)throw new Error(payload.error??"Unable to preview this command.");setPreview(payload.preview)}catch(error){notify(error instanceof Error?error.message:"Unable to preview this command.","error")}finally{setBusy(null)}}
  async function executeCommand(){if(!preview?.id)return;setBusy("execute");try{const response=await fetch("/api/approver/commands",{method:"POST",headers:{"content-type":"application/json","x-keel-ai-request":"1"},body:JSON.stringify({mode:"execute",commandId:preview.id,actorId:workspace.actor.id,actorName:workspace.actor.name})});const payload=await response.json() as {result?:{kind:string;approved?:string[]};error?:string};if(!response.ok||!payload.result)throw new Error(payload.error??"Unable to confirm this command.");notify(payload.result.kind==="set_limit"?"Policy limit updated and exception flags recalculated.":`${payload.result.approved?.length??0} matching claims approved and audited.`,"success");setPreview(null);await onChanged()}catch(error){notify(error instanceof Error?error.message:"Unable to confirm this command.","error")}finally{setBusy(null)}}
  return <section className="command-desk operational-card"><div className="card-heading"><div><small>Guarded AI workflow</small><h2>Command desk</h2></div><Bot size={20}/></div><p className="command-explainer">AI interprets one rule. Keel calculates exact matches from saved claims. Nothing changes until you confirm the preview.</p><div className="command-suggestions"><button type="button" onClick={()=>{setPrompt("Approve submitted Travel claims below €100");setPreview(null)}}>Approve Travel below €100</button><button type="button" onClick={()=>{setPrompt("Set the Meals limit to €100");setPreview(null)}}>Set Meals limit to €100</button></div><label className="command-input"><span>Approver instruction</span><textarea rows={2} maxLength={500} value={prompt} onChange={event=>{setPrompt(event.target.value);setPreview(null)}}/></label><div className="command-controls"><label className="receipt-check"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>Send this instruction to OpenAI and save its preview in this local demo.</span></label><button type="button" className="primary-button" disabled={busy!==null||!consent||!prompt.trim()} onClick={previewCommand}>{busy==="preview"?<Loader2 size={16} className="spin"/>:<Sparkles size={16}/>}Preview command</button></div>{preview&&<div className={`command-preview ${preview.kind==="unsupported"?"command-unsupported":""}`} aria-live="polite"><strong>{preview.summary}</strong>{preview.matches.length>0&&<ul>{preview.matches.map(item=><li key={item.id}><span>{item.merchant}</span><b>{formatMoney(item.amountMinor,item.currency)}</b></li>)}</ul>}<p>{preview.kind==="approve_matching"?"Only these still-submitted records can be approved. A changed claim is skipped at confirmation.":preview.kind==="set_limit"?"The new limit recalculates policy exceptions; it does not approve a claim.":"Try a supported approval or category-limit instruction."}</p>{preview.id&&<button type="button" className="primary-button" disabled={busy!==null} onClick={executeCommand}>{busy==="execute"?<Loader2 size={16} className="spin"/>:<Check size={16}/>}Confirm {preview.kind==="set_limit"?"policy update":`${preview.matches.length} approval${preview.matches.length===1?"":"s"}`}</button>}</div>}</section>;
}
