"use client";

import { Loader2, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import business from "@/config/business.json";
import type { WorkspacePayload } from "@/components/KeelApp";
import { formatMoney } from "@/lib/finance.mjs";

export function PolicyPanel({workspace,onChanged,notify}:{workspace:WorkspacePayload|null;onChanged:()=>Promise<unknown>;notify:(message:string,tone:"success"|"error")=>void}){
  const approver=business.approvers[0];const categories=useMemo(()=>workspace?.policy.categories??business.categories.map(item=>({...item,source:"configuration",updatedAt:null})),[workspace]);
  const [category,setCategory]=useState(categories[0]?.name??"");const [amount,setAmount]=useState(categories[0]?(categories[0].limitMinor/100).toFixed(2):"");const [saving,setSaving]=useState(false);
  function chooseCategory(name:string){setCategory(name);const selected=categories.find(item=>item.name===name);if(selected)setAmount((selected.limitMinor/100).toFixed(2))}
  async function updateLimit(){if(!workspace)return;setSaving(true);try{const response=await fetch("/api/policy",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({category,amount,actorId:workspace.actor.id,actorName:workspace.actor.name})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"Unable to update this policy limit.");notify(`${category} limit updated.`,"success");await onChanged()}catch(error){notify(error instanceof Error?error.message:"Unable to update this policy limit.","error")}finally{setSaving(false)}}
  return <section className="policy-page"><div className="policy-intro"><ShieldCheck size={23}/><div><h2>Configured expense limits</h2><p>Limits flag exceptions for review; they never silently approve a claim. The configured primary approver is {approver?.name??"not set"}.</p></div></div>{workspace?.role==="approver"&&<div className="policy-editor"><div><span className="eyebrow">Direct control</span><h3>Change a category limit</h3><p>Use this control when AI is unavailable. Changes are audited and recalculate exception flags.</p></div><label><span>Category</span><select value={category} onChange={event=>chooseCategory(event.target.value)}>{categories.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label><span>Limit ({workspace.policy.currency})</span><input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} pattern="[0-9]+([.][0-9]{1,2})?"/></label><button type="button" className="primary-button" disabled={saving} onClick={updateLimit}>{saving?<Loader2 size={16} className="spin"/>:<ShieldCheck size={16}/>}Update limit</button></div>}<div className="policy-grid">{categories.map(item=><article key={item.name}><span>{item.name}</span><strong>{formatMoney(item.limitMinor,workspace?.policy.currency??business.defaultCurrency)}</strong><small>{item.source==="approver"?"approver override":"configured"} · per claim</small></article>)}</div><div className="policy-safeguards"><h3>Workflow safeguards</h3><ul><li>Employees can create, edit, and submit only their own demo claims.</li><li>Approvers see policy exceptions before making a decision.</li><li>Finance can schedule or record only approved reimbursements.</li><li>“Paid” is an immutable finance record, not a bank transfer.</li></ul></div></section>;
}
